### ISSUE TITLE
After 1 game, when you queue up for game 2...

### ISSUE THREAD

**Issue by princessGasmask** [SightstoneOfficial/LegendaryClient#341] opened 2015-04-28 21:44 UTC
...the client will show that you are in queue twice. It will show "In Queue 0:09" and then "In Queue 49:30", or however long your last game was. You will have to close and relaunch the client or else you will crash on champ select of second game.

**Comment by secretdataz** [comment] 2015-05-12 03:34
Duplicate of #208

**Closed as completed by secretdataz** 2015-05-12 03:34 UTC
Labels: duplicate
